name: Latest blog posts and StackOverflow activity

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch and update blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: |
            https://medium.com/feed/@aryangupta1105
            https://stackoverflow.com/feeds/user/YOUR_SO_ID
