name: Spotify Now Playing

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update README with Spotify
        uses: sh5rk/spotify-now-playing-readme@v1
        with:
          refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
